import type { UIConfig } from "../types.ts";

export const bottomDockConfig: UIConfig["bottomDock"] = {
    panel: {
        fill: 0xe9e5dc,
        border: 0x6f6a61,
        borderWidth: 2,
        radius: 12,
        glossFill: 0xffffff,
        glossAlpha: 0.04,
        headerFill: 0xf4f2ec,
        headerBorder: 0x746e64,
        titleText: 0x2f2b27,
        bodyText: 0x3f3a34,
        inset: 3,
        fontFamily: "Noto Sans",
        titleFontSize: 15,
        bodyFontSize: 13,
        captionFontSize: 10,
    },
    shell: {
        fill: 0xd7d1c6,
        border: 0x6f6a61,
        borderWidth: 2,
        radius: 12,
        glossFill: 0xffffff,
        glossAlpha: 0.04,
    },
    slot: {
        fill: 0x9bb4c4,
        border: 0x5d7488,
        borderWidth: 2,
        radius: 10,
        glossFill: 0xffffff,
        glossAlpha: 0.07,
        activeFill: 0x6eb84f,
        activeBorder: 0x155e32,
    },
    rail: {
        fill: 0xcfc9be,
        radius: 10,
        dividerFill: 0x8f897e,
    },
    chip: {
        fill: 0x2f629f,
        border: 0xffffff,
        text: 0xffffff,
        radius: 4,
    },
    timer: {
        fill: 0xeeeae1,
        border: 0x6f6a61,
        stripFill: 0xd8d2c7,
        text: 0x2f2b27,
        subtext: 0x555049,
    },
};
