import type { UIConfig } from "../types.ts";

const RHYTHM = 4;
const SHARED_RAIL_HEIGHT = 90;
const RIGHT_RAIL_PANEL_WIDTH = 286;

export const hudConfig: UIConfig["hud"] = {
    padding: RHYTHM * 3,
    gap: RHYTHM * 2,
    playerPanel: {
        width: 286,
        rowHeight: SHARED_RAIL_HEIGHT + RHYTHM,
        headerOffset: RHYTHM * 3,
        scaleDefault: 1,
        scaleCrowded: 1,
        crowdedThreshold: 4,
        highlightRowHeight: SHARED_RAIL_HEIGHT,
    },
    rightRail: {
        width: RIGHT_RAIL_PANEL_WIDTH + RHYTHM * 2,
        bottomInset: RHYTHM * 2,
        topInset: RHYTHM * 2,
    },
    gameLog: {
        width: RIGHT_RAIL_PANEL_WIDTH,
        height: 298,
        visibleRows: 11,
    },
    chat: {
        laneWidth: RIGHT_RAIL_PANEL_WIDTH,
        laneHeight: 40,
        windowWidth: 268,
        windowHeight: 180,
        minWindowBottom: 250,
        popupRightInset: 20,
        popupTailInset: 50,
        inputInsetRight: RHYTHM * 6,
        inputInsetBottom: 256,
        inputHeight: RHYTHM * 7,
        inputBorderWidth: 2,
        inputHorizontalPadding: RHYTHM,
    },
    resourceBank: {
        width: RIGHT_RAIL_PANEL_WIDTH,
        height: 72,
    },
    bottomRail: {
        leftInset: RHYTHM * 3,
        bottomInset: RHYTHM * 2,
        gap: RHYTHM * 2,
        handHeight: SHARED_RAIL_HEIGHT,
        handMinWidth: 260,
        handMaxWidth: 760,
    },
    actionBar: {
        innerOffset: RHYTHM * 3,
        buttonSpacing: 74,
        buttonCount: 5,
        height: SHARED_RAIL_HEIGHT,
        buttonWidth: 66,
        buttonInset: 12,
        countWidth: 20,
        countHeight: 19,
        countFontSize: 13,
        stackGap: RHYTHM * 2,
    },
    dice: {
        rightRailGap: 34,
        aboveActionBarGap: RHYTHM * 4,
        minTopInset: 20,
    },
    misc: {
        bankSize: 90,
        bankTopMin: 10,
        devConfirmationOffsetY: 360,
        specialBuildOffsetX: 100,
        specialBuildOffsetY: 260,
        spectatorsX: 60,
        spectatorsY: 20,
        endTurnSlotIndex: 4,
        timerAboveEndTurnGap: RHYTHM * 2,
        diceAboveTimerGap: RHYTHM * 2,
        statusAboveDiceGap: RHYTHM * 3,
        statusWidth: 224,
        statusHeight: 40,
        timerWidth: 72,
        timerHeight: 36,
        statusLeftOfTimerGap: 4,
        shipAboveStatusGap: RHYTHM * 2,
        timerRightNudge: 6,
    },
};
