import type { UIConfig } from "../types.ts";

export const hudConfig: UIConfig["hud"] = {
    padding: 12,
    gap: 8,
    playerPanel: {
        width: 250,
        rowHeight: 80,
        headerOffset: 15,
        scaleDefault: 1.08,
        scaleCrowded: 1,
        crowdedThreshold: 4,
        highlightRowHeight: 79,
    },
    rightRail: {
        width: 292,
        bottomInset: 6,
        topInset: 4,
    },
    gameLog: {
        width: 270,
        height: 300,
        visibleRows: 13,
    },
    chat: {
        laneWidth: 270,
        laneHeight: 34,
        windowWidth: 250,
        windowHeight: 160,
        minWindowBottom: 250,
        popupRightInset: 20,
        popupTailInset: 50,
        inputInsetRight: 25,
        inputInsetBottom: 256,
        inputHeight: 25,
        inputBorderWidth: 2,
        inputHorizontalPadding: 4,
    },
    resourceBank: {
        width: 270,
        height: 66,
    },
    bottomRail: {
        leftInset: 10,
        bottomInset: 8,
        gap: 8,
        handHeight: 90,
        handMinWidth: 260,
        handMaxWidth: 900,
    },
    actionBar: {
        innerOffset: 12,
        buttonSpacing: 74,
        buttonCount: 5,
        height: 90,
        buttonWidth: 66,
        buttonInset: 12,
        countWidth: 20,
        countHeight: 19,
        countFontSize: 13,
        stackGap: 10,
    },
    dice: {
        rightRailGap: 34,
        aboveActionBarGap: 18,
        minTopInset: 20,
    },
    misc: {
        bankSize: 90,
        bankTopMin: 10,
        devConfirmationOffsetY: 360,
        specialBuildOffsetX: 100,
        specialBuildOffsetY: 260,
        spectatorsX: 60,
        spectatorsY: 20,
    },
};
