import type { UIConfig } from "../types.ts";

export const hudConfig: UIConfig["hud"] = {
    padding: 10,
    gap: 8,
    playerPanel: {
        width: 286,
        rowHeight: 96,
        headerOffset: 12,
        scaleDefault: 1,
        scaleCrowded: 1,
        crowdedThreshold: 4,
        highlightRowHeight: 92,
    },
    rightRail: {
        width: 300,
        bottomInset: 8,
        topInset: 6,
    },
    gameLog: {
        width: 288,
        height: 298,
        visibleRows: 12,
    },
    chat: {
        laneWidth: 288,
        laneHeight: 40,
        windowWidth: 268,
        windowHeight: 180,
        minWindowBottom: 250,
        popupRightInset: 20,
        popupTailInset: 50,
        inputInsetRight: 25,
        inputInsetBottom: 256,
        inputHeight: 25,
        inputBorderWidth: 2,
        inputHorizontalPadding: 4,
    },
    resourceBank: {
        width: 288,
        height: 72,
    },
    bottomRail: {
        leftInset: 10,
        bottomInset: 8,
        gap: 8,
        handHeight: 90,
        handMinWidth: 260,
        handMaxWidth: 760,
    },
    actionBar: {
        innerOffset: 12,
        buttonSpacing: 74,
        buttonCount: 5,
        height: 90,
        buttonWidth: 66,
        buttonInset: 12,
        countWidth: 20,
        countHeight: 19,
        countFontSize: 13,
        stackGap: 10,
    },
    dice: {
        rightRailGap: 34,
        aboveActionBarGap: 18,
        minTopInset: 20,
    },
    misc: {
        bankSize: 90,
        bankTopMin: 10,
        devConfirmationOffsetY: 360,
        specialBuildOffsetX: 100,
        specialBuildOffsetY: 260,
        spectatorsX: 60,
        spectatorsY: 20,
        endTurnSlotIndex: 4,
        timerAboveEndTurnGap: 6,
        diceAboveTimerGap: 6,
        statusAboveDiceGap: 10,
        statusWidth: 224,
        statusHeight: 40,
        timerWidth: 72,
        timerHeight: 36,
        statusLeftOfTimerGap: 4,
        shipAboveStatusGap: 6,
        timerRightNudge: 6,
    },
};
