import type { UIConfig } from "../types.ts";

export const overlaysConfig: UIConfig["overlays"] = {
    pendingAction: {
        x: 20,
        y: 20,
        width: 450,
        height: 40,
        closeButtonSize: 38,
        textX: 10,
        textY: 20,
        fontSize: 20,
    },
    setupPreview: {
        buttonSize: 52,
        singleWidth: 62,
        dualWidth: 118,
        height: 62,
        offsetY: 78,
        padding: 5,
        secondaryButtonX: 61,
    },
    chooseDice: {
        dieWidth: 40,
        gap: 5,
        padding: 10,
        rowGap: 15,
        anchorX: 20,
        bottomOffset: 140,
    },
    chooseBuildable: {
        singleWidth: 76,
        dualWidth: 140,
        height: 62,
        defaultX: 20,
        bottomOffset: 140,
        margin: 10,
        topOffset: 16,
        bottomPlacementOffset: 16,
        buttonSize: 52,
        buttonY: 6,
        singleButtonX: 12,
        dualLeftX: 10,
        dualRightX: 74,
    },
    gameOver: {
        width: 450,
        playerRowHeight: 95,
        extraHeight: 80,
        titleFontSize: 32,
        titleY: 30,
        pivotYDivisor: 4,
    },
};
