import type { UIConfig } from "../types.ts";

export const tradeConfig: UIConfig["trade"] = {
    editor: {
        offerWidth: 440,
        windowHeight: 90,
        cardWidth: 52,
        leftX: 20,
        panelGap: 20,
        rowGap: 10,
        bottomOffset: 20,
        askExtraOffset: 110,
        compactAskBaseWidth: 440,
        ckAskBaseWidth: 440,
        ckPossibleAskWidth: 440,
        basePossibleAskWidth: 440,
        contentInsetLeft: 70,
        railWidth: 56,
        railRadius: 14,
        iconSize: 26,
        surfaceFill: 0xe9e4db,
        surfaceBorder: 0x0f79c8,
        surfaceBorderWidth: 3,
        railFill: 0x10bfd0,
        actionRailGap: 8,
    },
    offers: {
        laneRightOffset: 430,
        laneTop: 20,
        laneGap: 70,
        scale: 0.8,
        cardWindowWidth: 250,
        cardWindowHeight: 80,
        cardWidth: 40,
        panelGap: 30,
        markerPlusX: 263,
        markerPlusY: -8,
        markerMinusX: 260,
        markerMinusY: -20,
        acceptAvatarStep: 50,
        acceptPanelPadding: 10,
        acceptPanelHeight: 80,
        counterButtonWindowSize: 42,
        offererPanelWidth: 60,
        offererPanelHeight: 80,
        offererOffsetX: -70,
        enterAnimationOffsetX: 40,
    },
};
